### ISSUE TITLE
What parts of the code contain the most time consuming computation 

### ISSUE THREAD

**Issue by hbake001** [kbatseli/MVMALS#1]
Hi Kim,
I'm trying to adapt your code to run it on a cluster. I think that most heavy code portion starts in the for loop at line 75 in `mvmals.m` file: 

```
        for i=M:N+M-1
            ui=zeros(p*M+1,1);
            ui(1)=1;
            for j=1:M
.....
```

However, because the way that the matrix `A` was used:
`A((i-M)*l+1:(i-M+1)*l,:)=mkron(vk2',mkron(ui',2),vk1);
` `parfor `doesn't work with it. Can you help me with this?

**Comment by kbatseli** [comment]
Hi, can you explain which part of the code you are trying to speed up by running it on a cluster? Actually, the construction of the A matrix in mvmals.m can be made faster by retaining earlier contractions in two cells. This avoids the nested for-loop and is already implemented in the mvals.m method. The two cells are called Vp and Vm. You might want to check out the implementation of mvals.m and adapt mvmals.m in a similar way.

**Comment by hbake001** [comment]
@kbatseli Thanks, actually I realized that your implementation is well vectorized and using  `parfor` will decrease the processor utilization.
