### ISSUE TITLE
Why did you limit the iteration to only 2? 

### ISSUE THREAD

**Issue by hbake001** [kbatseli/MVMALS#2]
Hi, 

In your mvals.m you limited the iteration to 2 as the following 

```
while itr<2 || ((e(itr) < e(itr-1)) && (itr < MAXITR) && e(itr) > THRESHOLD)
    updateTT;
    updatesweep;
    % only check residual after 1 half sweep
    if (sweepindex==d) || (sweepindex==1) % half a sweep
        itr=itr+1;
        yhat=sim_volterraTN(u,TN);
        yhat=reshape(yhat',[N*l,1]);
        e(itr)=norm(y(l*M+1:end)-yhat(l*M+1:end))/norm(y(l*M+1:end));
    end    
end  
```

I assumed that this is a bug and modified the code such that it accepts the possible iteration number as a parameter. It performs better using my modification, so would you consider that as a bug or am I missing something here? 

An off-topic question: I tried to run the algorithm using 8 memory units and d = 8 (number of Volterra terms) The algorithm asked for 128 Gb of RAM, are you aware of that?

**Comment by kbatseli** [comment]
Thank you for the comments. The number of iterations is not limited to 2. From the moment itr<2 is false, more iterations occur as long as  ((e(itr) < e(itr-1)) && (itr < MAXITR) && e(itr) > THRESHOLD) is true. You are of course free to modify the code in any way that suits your needs.

At which line of mvals.m does MATLAB crash, asking for 128 Gb of RAM?
